version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "minesweeper-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iriw7pcgy02w"
s3_prefix = "minesweeper-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "minesweeper"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iriw7pcgy02w"
s3_prefix = "minesweeper"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"prod\""
image_repositories = []
